### ISSUE TITLE
Make run-on-save toggleable?

### ISSUE THREAD

**Issue by thenickcox** [heavenshell/vim-prettier#4]
First, thanks a lot for this. I had a few issues with the other prettier plugins, namely performance. Your async implementation of this made it workable.

One thing I like about the Syntastic plugin is that the run-on-save mode is toggleable. It'd be nice to be able to turn that off.

I'm actually thinking it could be a modification to the one-liner you have in the docs.

(Warning: My vimscript is awful.)

Could it change this:

```vim
autocmd BufWritePost *.js,*.jsx call prettier#run(1)
```

To something like this?

```vim
function! g:TogglePrettierOnSave()
  if (doPrettier == true)
    autocmd BufWritePost *.js,*.jsx call prettier#run(1)
  else
    let doPrettier = false
  endif
endfunc

" could be <leader>pp or anything else
nnoremap <leader>pp :call g:TogglePrettierOnSave()<cr>
```

(I know this actually won't work, but I can't figure out how to unset an `autocmd`. Like I said, I have no idea what I'm doing when it comes to vimscript.

If you let me know the correct form of that function, I'm happy to submit a PR with a change to the README updating it with this option.

Thanks again!

**Comment by thenickcox** [comment]
Update:

Although it's not the best way to do it, something like this appears to work:

```vim
function! g:TogglePrettierOnSave()
  if (exists("prettierMode"))
    let prettierMode = "off"
  else
    let prettierMode = "on"
  end
  if (prettierMode == "on")
    autocmd BufWritePost *.js,*.jsx call prettier#run(1)
  else
    autocmd! BufWritePost *.js,*.jsx call prettier#run(1)
  endif
endfunc
```

**Comment by heavenshell** [comment]
@thenickcox Sorry for late response.
I don't use run on save(I manually type `:Prettier` command).
May be like this?

Put followings to your .vimrc
```vim
let s:prettier_enabled = 0 " Default is off(If you want default on, turn this to 1)
function! s:prettier_toggle()
  let enabled = !get(s:, 'pretter_enabled')
  augroup augroup_prettier
    if enabled
      autocmd!
      autocmd BufWritePost *.js,*.jsx call prettier#run(1)
    endif
  augroup END
endfunction
command! -buffer PrettierToggle :call s:prettier_toggle()
```
```
:PrettierToggle
```

**Comment by thenickcox** [comment]
So sorry, I've been out for the holidays. I'll try to check this when I get back. Thanks!

**Comment by heavenshell** [comment]
Answered. If this answer did not solve, please reopen this.
