### ISSUE TITLE
'+channel and +job are required for prettier.vim'

### ISSUE THREAD

**Issue by lazamar** [heavenshell/vim-prettier#5]
I Just installed vim-prettier through `vim-plug` and I'm getting this error. 
I can see that in `prettier.vim` says this is a version check, but I don't understand version of what. How can I solve this?

**Comment by heavenshell** [comment]
@lazamar 
vim-prettier requires Vim8(NeoVim not supported) and `job` feature.
Could you show me `:version`?

**Comment by lazamar** [comment]
Ah, I'm using neovim. :/ 
`NVIM v0.2.3-dev`

Is there any way to get it working in neovim?

**Comment by heavenshell** [comment]
@lazamar 

> Is there any way to get it working in neovim?

Vim8's job and NeoVim's job are different api.

I'm Sorry. I don't have any plan to support NeoVim(I don't use NeoVim).
Maybe you can use <https://github.com/sbdchd/neoformat>.
